package main.java;

public enum Faction {
  ARABY, BRETONNIA, CHAOS_WARRIOR, DARK_ELF, DWARF,

  ESTALIA, FIMIR, HIGH_ELF, ORC, GOBLIN,

  THE_EMPIRE, HALFLING, KISLEV, LIZARDMEN, OGRE,

  SKAVEN, TILEA, TOMB_KING, VAMPIRE_COUNT,

  WOOD_ELF, DEMON, CHAOS_DWARF
}
